import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Chat | SD-distribuidora',
  description: 'Generated by next',
}

interface RequestLayoutProps {
  children: React.ReactNode;
}

export default function RequestLayout({ children }: RequestLayoutProps) {
  return (
    <html lang="pt-pt">
      <body>{children}</body>
    </html>
  )
}
