import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Entre ou Cadastre',
  description: 'Generated by next',
}

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-pt">
      <body >{children}</body>
    </html>
  )
}
