import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'SD-distribuidora',
  description: 'Generated by next',
  icons: { icon: './logoS.png'}
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-pt">
      <body >{children}</body>
    </html>
  )
}
